version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=production
            - APP_KEY=base64:yDbWdhS3MXNWVxhi7Ob3Fg8ZW3qF3BhoHYFXudi9VN4=
            - APP_DEBUG=false
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=finalwtc
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: finalwtc
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-uroot", "-proot" ]
            interval: 5s
            timeout: 10s
            retries: 5

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8082:80"
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

volumes:
    mysql_data:
