services:
    app:
        build: .
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
        depends_on:
            db:
                condition: service_healthy
        environment:
            - DB_HOST=db
            - DB_PORT=3306

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: finalwtc
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-uroot",
                    "-proot",
                ]
            interval: 5s
            timeout: 10s
            retries: 5

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

volumes:
    mysql_data:
